// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMI8wem8avcvGphR2PTvTOwZoZoh7n0e4',
    appId: '1:91001421934:web:330fcf30979e6402d9a67f',
    messagingSenderId: '91001421934',
    projectId: 'moazez-production',
    authDomain: 'moazez-production.firebaseapp.com',
    storageBucket: 'moazez-production.firebasestorage.app',
    measurementId: 'G-1XX36BGWXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPWWJrK-MhOUzA1YJIUQN9Ckl-GTq-84E',
    appId: '1:91001421934:android:7c59987a76eea220d9a67f',
    messagingSenderId: '91001421934',
    projectId: 'moazez-production',
    storageBucket: 'moazez-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARiMuHwr8f0f4TQkzvPlM3VjZ2TkVZ6AE',
    appId: '1:91001421934:ios:b52318c6c8cbc50dd9a67f',
    messagingSenderId: '91001421934',
    projectId: 'moazez-production',
    storageBucket: 'moazez-production.firebasestorage.app',
    iosBundleId: 'sa.moazez.nedaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARiMuHwr8f0f4TQkzvPlM3VjZ2TkVZ6AE',
    appId: '1:91001421934:ios:6d6226016e16b9a9d9a67f',
    messagingSenderId: '91001421934',
    projectId: 'moazez-production',
    storageBucket: 'moazez-production.firebasestorage.app',
    iosBundleId: 'com.example.ndaaaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMI8wem8avcvGphR2PTvTOwZoZoh7n0e4',
    appId: '1:91001421934:web:c6cb9d5edbb67b67d9a67f',
    messagingSenderId: '91001421934',
    projectId: 'moazez-production',
    authDomain: 'moazez-production.firebaseapp.com',
    storageBucket: 'moazez-production.firebasestorage.app',
    measurementId: 'G-PJC3VC6Z8W',
  );
}
